language: ruby # Need python and node

cache:
  bundler: true
  npm: true

rvm:
  - 2.6.2

# Setup pandoc for building
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install pandoc-citeproc

script:
  - cd site
  - ruby --version
  - gem install bundler:1.17.2
  - npm install
  - npm run build
  - htmlproofer ./_site

# Branch whitelist, only for GitHub Pages
branches:
  only:
  - develop

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # Route your build to the container-based infrastructure for a faster build
