# For local development; disable assets and sets up live reloading etc

environment: development

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

host: 0.0.0.0
port: 4002

incremental: true
livereload: true

sass:
  style: expanded

# For development skip compilation of assets
assets:
  raw_precompile:
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
  plugins:
    img:
      optim: # The preset used by @optim tag; disable those used for production
        default:
          jpegrecompress: false
          pngquant: false
